# Generated by Django 3.0.8 on 2021-11-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211128_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Room_DP',
        ),
    ]
